[global]
error_log = /proc/self/fd/2
daemonize = no
;request_terminate_timeout = 1h

[www]
access.log = /proc/self/fd/1
clear_env = no
catch_workers_output = yes
decorate_workers_output = no
ping.path = /fpm-ping
pm.status_path = /fpm-status
